### ISSUE TITLE
Use File.exists() to determine if the file exists, and if true, write to a new file

### ISSUE THREAD

**Issue by wsh32** [4201VitruvianBots/PathGen#1]
https://github.com/VitruvianBots/PathGen/blob/c1ec49305521dd5632988051bb0fcc0cbd924e6c/src/main/java/PathGen.java#L99

See https://stackoverflow.com/questions/1816673/how-do-i-check-if-a-file-exists-in-java and https://github.com/nerdherd/PowerUp2018/blob/f6d7371b26984c926d67f415c0b48b8d1904f8b4/src/com/team687/frc2018/subsystems/Wrist.java#L206 for examples.

**Comment by jonathandao0** [comment]
So this is a bit more complicated issue than trying to figure out if a file exists. With my current method, I'm trying to figure out if I should even generate a given trajectory based on its waypoints/configuration. If I was just checking if the file exists, it would never overwrite the file if I was just adjusting a few parameters on a path (Plus, it would make referencing the name of the file from the robot much harder).

The main issue comes from line 88:
https://github.com/VitruvianBots/PathGen/blob/c1ec49305521dd5632988051bb0fcc0cbd924e6c/src/main/java/PathGen.java#L88

The generation of the trajectory can take a long time, especially when you're iterating over all the paths. During champs, due to the limited time you have on the practice fields, the easiest way of avoiding the generation time was comment out everything I wasn't working on to avoid generating that stuff. This works until you've finished tuning a path and then want to switch over to a totally different path, which costs you time as you have to take time to think about what you need/don't need and then adjust comments. With the way I have this code set up, if you adjust any of the path parameters, the code checks all the parameters with what it previously recorded for that path (in the form of a serialized .ser file). If it detects a difference in the path or its parameters, it then generates the path and writes the file, otherwise it skips it. That way, the person working on this only has to worry about adjusting the path in code and nothing else.

As an example of its effectiveness, generating all the path files from scratch takes up ~10 seconds if you had to do it every time. If you adjust a single path's parameter, it goes through the entire code in < 0.5 seconds. This makes a lot of difference when you're being clocked for 10 minutes on a practice field at an event.
