### ISSUE TITLE
Magic number in PathGen.java

### ISSUE THREAD

**Issue by wsh32** [4201VitruvianBots/PathGen#2]
https://github.com/VitruvianBots/PathGen/blob/c1ec49305521dd5632988051bb0fcc0cbd924e6c/src/main/java/PathGen.java#L91

```java
modifier = new TankModifier(trajectory).modify(0.7639);
```

What does 0.7639 mean? Can you put it into a variable so it is more clear what it is and easy to modify? If this is a tuned value, can you put it onto dash?

**Comment by jonathandao0** [comment]
The modifier value in the Pathfinder library basically generates two trajectories from the single trajectory of the path. The two trajectories you get correspond to the left and right side of the wheels. The number we used in modify is the wheelbase (width) of the robot in yards, since that was the unit of measurement we used as a standard. I've heard that adjusting this value from what it actually is can make it easier for some robots to follow a path, but we didn't have to do that.

We should be switching this to feet after Beach Blitz to make it easier to understand/modify. This was in yards because we thought that putting it in feet was causing us issues early on when playing with Pathfinder.
